language: python

python:
    - 3.7

git:
    depth: false

before_install:
    # alias package
    - name=`basename $TRAVIS_BUILD_DIR`
    - package=$TRAVIS_BUILD_DIR/$name
    - export PYTHONPATH=$package:$PYTHONPATH

    # upgrade pip 
    - pip install --upgrade pip

    # install flake8
    - pip install flake8

    # install isort 
    - pip install isort

    # install mypy 
    - pip install mypy 

    # log setup 
    - echo $PATH
    - echo $PYTHONPATH
    - echo $TRAVIS_BUILD_DIR
    - ls 
    - echo $PACKAE

install:
    - pip install -e .

script:
    - mypy $TRAVIS_BUILD_DIR/$name
    - py.test -rf $TRAVIS_BUILD_DIR/$name/tests/test_reading.py

notifications:
    email: false
