language: python

python:
    - 3.7

git:
    depth: false

before_install:
    # name working directory 
    - LOCATION=`pwd`

    # alias package
    - PACKAGE=`pwd`/iChing
    - export PYTHONPATH=$PACKAGE:$PYTHONPATH
    - export PATH=$PACKAGE/scr/:$PATH

    # upgrade pip 
    - pip install --upgrade pip

    # install flake8
    - pip install flake8

    # install isort 
    - pip install isort

    # log setup 
    - echo $PATH
    - echo $PYTHONPATH
    - echo $TRAVIS_BUILD_DIR
    - ls 
    - echo $PACKAE

install:
    - pip install -e .

script:
    - mypy $TRAVIS_BUILD_DIR/$name
    - py.test -rf $TRAVIS_BUILD_DIR/$name/test_reading.py

notifications:
    email: false
