language: python

python:
    - 3.7

git:
    depth: false

before_install:

    #get package name
    - name=`basename $TRAVIS_BUILD_DIR`

install:
    - pip install -r requirements.txt
    - pip insall -e .

script:
    - mypy $TRAVIS_BUILD_DIR/$name
    - py.test -rf $TRAVIS_BUILD_DIR/$name/test.py

notifications:
    email: false
